<a href="https://colab.research.google.com/github/raheeltahir55/CE888/blob/main/Lab8/Lab8_Task_FineTuning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!wget 'https://github.com/sagihaider/CE888_2021/raw/main/Lab_8/data.zip'

--2021-05-01 17:36:27--  https://github.com/sagihaider/CE888_2021/raw/main/Lab_8/data.zip
Resolving github.com (github.com)... 192.30.255.112
Connecting to github.com (github.com)|192.30.255.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/sagihaider/CE888_2021/main/Lab_8/data.zip [following]
--2021-05-01 17:36:27--  https://raw.githubusercontent.com/sagihaider/CE888_2021/main/Lab_8/data.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20194537 (19M) [application/zip]
Saving to: ‘data.zip’

data.zip            100%[===================>]  19.26M  48.3MB/s    in 0.4s    

2021-05-01 17:36:29 (48.3 MB/s) - ‘data.zip’ saved [20194537/20194537]



In [2]:
!unzip data.zip

Archive:  data.zip
   creating: data/
   creating: data/cats/
  inflating: data/cats/cat.1.jpg     
  inflating: data/cats/cat.10.jpg    
  inflating: data/cats/cat.100.jpg   
  inflating: data/cats/cat.101.jpg   
  inflating: data/cats/cat.102.jpg   
  inflating: data/cats/cat.103.jpg   
  inflating: data/cats/cat.104.jpg   
  inflating: data/cats/cat.105.jpg   
  inflating: data/cats/cat.106.jpg   
  inflating: data/cats/cat.107.jpg   
  inflating: data/cats/cat.108.jpg   
  inflating: data/cats/cat.109.jpg   
  inflating: data/cats/cat.11.jpg    
  inflating: data/cats/cat.110.jpg   
  inflating: data/cats/cat.111.jpg   
  inflating: data/cats/cat.112.jpg   
  inflating: data/cats/cat.113.jpg   
  inflating: data/cats/cat.114.jpg   
  inflating: data/cats/cat.115.jpg   
  inflating: data/cats/cat.116.jpg   
  inflating: data/cats/cat.117.jpg   
  inflating: data/cats/cat.118.jpg   
  inflating: data/cats/cat.119.jpg   
  inflating: data/cats/cat.12.jpg    
  inflating: data/cats/cat

In [4]:
import os
# Get all the paths
data_dir_list = os.listdir('/content/data/Humans')
#print(data_dir_list)
path, dirs, files = next(os.walk("/content/data/Humans"))
file_count = len(files)
print(file_count)

202


In [5]:
# Make new base directory
original_dataset_dir = '/content/data'
base_dir = '/content/cats_dogs_horses_humans'
os.mkdir(base_dir)

In [6]:
original_dataset_dir_cat= '/content/data/cats'
original_dataset_dir_dog=  '/content/data/dogs'
original_dataset_dir_horse= '/content/data/horses'
original_dataset_dir_human= '/content/data/Humans'

In [7]:
train_dir = os.path.join(base_dir, 'train')
os.mkdir(train_dir)

validation_dir = os.path.join(base_dir, 'validation')
os.mkdir(validation_dir)

test_dir = os.path.join(base_dir, 'test')
os.mkdir(test_dir)

In [8]:
import shutil
fnames = ['cat.{}.jpg'.format(i) for i in range(1,120)]
for fname in fnames:
    src = os.path.join(original_dataset_dir_cat, fname)
    dst = os.path.join(train_dir, fname)
    #print(src,dst)
    shutil.copyfile(src, dst)
    
fnames = ['cat.{}.jpg'.format(i) for i in range(120, 160)]
for fname in fnames:
    src = os.path.join(original_dataset_dir_cat, fname)
    dst = os.path.join(validation_dir, fname)
    shutil.copyfile(src, dst)

fnames = ['cat.{}.jpg'.format(i) for i in range(160, 203)]
for fname in fnames:
    src = os.path.join(original_dataset_dir_cat, fname)
    dst = os.path.join(test_dir, fname)
    shutil.copyfile(src, dst)
    
fnames = ['dog.{}.jpg'.format(i) for i in range(1,120)]
for fname in fnames:
    src = os.path.join(original_dataset_dir_dog, fname)
    dst = os.path.join(train_dir, fname)
    shutil.copyfile(src, dst)

fnames = ['dog.{}.jpg'.format(i) for i in range(120, 160)]
for fname in fnames:
    src = os.path.join(original_dataset_dir_dog, fname)
    dst = os.path.join(validation_dir, fname)
    shutil.copyfile(src, dst)

fnames = ['dog.{}.jpg'.format(i) for i in range(160, 203)]
for fname in fnames:
    src = os.path.join(original_dataset_dir_dog, fname)
    dst = os.path.join(test_dir, fname)
    shutil.copyfile(src, dst)

In [9]:
import shutil
fnames = ['horse-{}.jpg'.format(i) for i in range(1,120)]
for fname in fnames:
    src = os.path.join(original_dataset_dir_horse, fname)
    dst = os.path.join(train_dir, fname)
    #print(src,dst)
    shutil.copyfile(src, dst)
    
fnames = ['horse-{}.jpg'.format(i) for i in range(120, 160)]
for fname in fnames:
    src = os.path.join(original_dataset_dir_horse, fname)
    dst = os.path.join(validation_dir, fname)
    shutil.copyfile(src, dst)

fnames = ['horse-{}.jpg'.format(i) for i in range(160, 203)]
for fname in fnames:
    src = os.path.join(original_dataset_dir_horse, fname)
    dst = os.path.join(test_dir, fname)
    shutil.copyfile(src, dst)
    
fnames = ['rider-{}.jpg'.format(i) for i in range(1,120)]
for fname in fnames:
    src = os.path.join(original_dataset_dir_human, fname)
    dst = os.path.join(train_dir, fname)
    shutil.copyfile(src, dst)

fnames = ['rider-{}.jpg'.format(i) for i in range(120, 160)]
for fname in fnames:
    src = os.path.join(original_dataset_dir_human, fname)
    dst = os.path.join(validation_dir, fname)
    shutil.copyfile(src, dst)

fnames = ['rider-{}.jpg'.format(i) for i in range(160, 203)]
for fname in fnames:
    src = os.path.join(original_dataset_dir_human, fname)
    dst = os.path.join(test_dir, fname)
    shutil.copyfile(src, dst)

In [10]:
import cv2
import numpy as np
from random import shuffle

IMG_SIZE = 224
LR = 1e-4

In [11]:
def label_img(img):
    img= img.replace('-', '.')
    word_label = img.split('.')[0]
    if word_label == 'dog': return 1
    elif word_label == 'cat': return 0
    elif word_label == 'horse': return 2
    elif word_label == 'rider': return 3

In [12]:
def createDataSplitSet(datapath):
    X=[]
    y=[]

    for img in os.listdir(datapath):
        label = label_img(img)
        # print(label)
        path = os.path.join(datapath, img)
        image = cv2.resize(cv2.imread(path), (IMG_SIZE, IMG_SIZE))
        image = cv2.normalize(image, None, alpha=0, beta=1, norm_type=cv2.NORM_MINMAX, dtype=cv2.CV_32F)

        X.append(np.array(image))
        y.append(label)

    return np.array(X), np.array(y)

In [13]:
train_X, train_y = createDataSplitSet(train_dir)
val_X, val_y = createDataSplitSet(validation_dir)
test_X, test_y = createDataSplitSet(test_dir)

In [14]:
## Xception
from tensorflow.keras.applications import EfficientNetB7
from tensorflow.keras.applications import VGG16
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.applications import Xception
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras import Model

img_input = Input(shape=(IMG_SIZE, IMG_SIZE, 3))

In [16]:
model=Xception(
    include_top=True,
    weights="imagenet",
    input_tensor=img_input,
    input_shape=None,
    pooling=None,
    classes=1000,
    classifier_activation="softmax",
)
model.summary()

91889664/91884032 [==============================] - 1s 0us/step
Model: "xception"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 224, 224, 3) 0                                            
__________________________________________________________________________________________________
block1_conv1 (Conv2D)           (None, 111, 111, 32) 864         input_1[0][0]                    
__________________________________________________________________________________________________
block1_conv1_bn (BatchNormaliza (None, 111, 111, 32) 128         block1_conv1[0][0]               
__________________________________________________________________________________________________
block1_conv1_act (Activation)   (None, 111, 111, 32) 0           block1_conv1_bn[0][0]            
__________________________

In [17]:
last_layer = model.get_layer('avg_pool').output
out = Dense(4, activation='softmax', name='output')(last_layer)  ## 4 classes
model = Model(img_input, out)

for layer in model.layers[:-5]:
	layer.trainable = False

model.summary()

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 224, 224, 3) 0                                            
__________________________________________________________________________________________________
block1_conv1 (Conv2D)           (None, 111, 111, 32) 864         input_1[0][0]                    
__________________________________________________________________________________________________
block1_conv1_bn (BatchNormaliza (None, 111, 111, 32) 128         block1_conv1[0][0]               
__________________________________________________________________________________________________
block1_conv1_act (Activation)   (None, 111, 111, 32) 0           block1_conv1_bn[0][0]            
______________________________________________________________________________________________

In [ ]:
# model.compile(loss='sparse_categorical_crossentropy',
#               optimizer='adam',
#               metrics=['acc'])

In [18]:
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['acc'])

In [19]:
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
my_callbacks = [
    EarlyStopping(monitor="val_loss", patience=10, restore_best_weights=True),
    ModelCheckpoint(filepath='efficientnetb7_model.h5', save_best_only=True),
]

In [20]:
import keras
y_train = keras.utils.to_categorical(train_y, 4)
y_val = keras.utils.to_categorical(val_y, 4)
y_test = keras.utils.to_categorical(test_y, 4)

In [21]:
print(train_y)

[1 3 3 0 2 3 0 1 2 3 2 2 0 2 0 2 3 3 0 3 1 1 3 3 3 0 2 0 0 3 0 0 3 3 1 2 2
 3 1 3 3 3 0 2 1 1 1 1 0 0 2 0 1 2 0 1 1 3 0 3 0 2 3 3 2 0 2 0 0 0 0 1 0 2
 1 2 1 0 0 3 1 3 2 2 0 2 1 2 2 1 0 3 0 1 0 0 1 2 2 1 2 2 1 1 0 3 2 0 2 2 0
 0 3 0 3 3 3 3 3 1 3 2 3 3 2 1 2 0 2 2 2 2 0 1 0 1 3 1 2 1 3 2 3 3 3 2 0 0
 2 3 3 2 1 0 1 0 1 2 3 3 0 1 1 3 3 1 1 1 3 2 0 2 1 2 3 2 0 2 0 1 3 0 3 0 1
 2 0 2 1 1 2 2 3 1 1 3 3 0 1 3 1 1 1 2 1 0 1 0 0 2 3 2 0 2 3 2 1 3 1 3 3 0
 2 3 2 2 3 1 1 2 0 1 3 2 0 3 0 2 3 2 0 2 0 1 1 1 1 1 3 2 0 1 2 0 1 1 2 3 1
 0 1 3 2 1 3 1 3 1 3 0 2 2 2 1 0 2 2 1 3 1 0 3 3 0 0 1 2 2 1 0 0 1 3 1 1 0
 3 3 2 1 0 3 3 3 3 3 0 3 3 0 1 1 1 3 2 1 0 2 2 2 1 0 0 1 0 2 0 2 0 0 2 3 3
 3 0 2 2 0 0 2 2 3 1 0 2 0 3 1 3 3 1 0 3 1 0 0 3 3 0 2 1 1 3 3 1 1 3 2 1 2
 1 0 0 3 3 3 3 2 2 2 0 2 2 1 0 2 2 2 3 1 3 1 2 3 3 3 2 1 3 3 0 1 1 3 0 0 0
 1 0 1 2 0 1 3 0 1 2 1 0 2 0 0 0 1 2 2 2 3 1 0 3 2 0 3 0 1 0 1 0 0 1 2 1 0
 0 3 0 2 1 0 3 1 1 2 2 1 2 0 2 2 1 1 3 3 3 2 0 0 3 1 3 1 0 2 2 2]


In [22]:
print(y_train)

[[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 ...
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]]


In [23]:
history = model.fit(train_X, y_train,
                               batch_size=10,
                               epochs=10, 
                               validation_data=(val_X, y_val),
                               callbacks=my_callbacks)

Epoch 1/10
48/48 [==============================] - 39s 89ms/step - loss: 0.4685 - acc: 0.8222 - val_loss: 0.0434 - val_acc: 0.9812
Epoch 2/10
48/48 [==============================] - 3s 58ms/step - loss: 0.0339 - acc: 0.9913 - val_loss: 0.0580 - val_acc: 0.9875
Epoch 3/10
48/48 [==============================] - 3s 57ms/step - loss: 0.0074 - acc: 1.0000 - val_loss: 0.0326 - val_acc: 0.9875
Epoch 4/10
48/48 [==============================] - 3s 57ms/step - loss: 0.0053 - acc: 1.0000 - val_loss: 0.0304 - val_acc: 0.9875
Epoch 5/10
48/48 [==============================] - 3s 58ms/step - loss: 0.0139 - acc: 0.9974 - val_loss: 0.0367 - val_acc: 0.9750
Epoch 6/10
48/48 [==============================] - 3s 58ms/step - loss: 0.0074 - acc: 1.0000 - val_loss: 0.0248 - val_acc: 0.9875
Epoch 7/10
48/48 [==============================] - 3s 58ms/step - loss: 0.0057 - acc: 1.0000 - val_loss: 0.0271 - val_acc: 0.9812
Epoch 8/10
48/48 [==============================] - 3s 58ms/step - loss: 0.0019 - 

In [24]:
accr = model.evaluate(test_X, y_test)
print('Test set\n  Loss: {:0.3f}\n  Accuracy: {:0.3f}'.format(accr[0],accr[1]))

6/6 [==============================] - 3s 241ms/step - loss: 0.1635 - acc: 0.9709
Test set
  Loss: 0.163
  Accuracy: 0.971
